### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "ilana15@gmail.com",
  "password": "1234"
}

### Login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ilana15@gmail.com",
  "password": "1234"
}

### Refresh a user token
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzhjZjhiNzQ2OTQ2YmYyZjlkZDE2YmEiLCJyYW5kb20iOjkxMTg4OCwiaWF0IjoxNzM3MjkxOTYxLCJleHAiOjE3Mzc4OTY3NjF9.haKweUQPoT9GRBiGda6d_PWoLbpbDoR9bR5isI1uXfk"
}

### Create a new post with an access token
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjk1NjM3OCwiaWF0IjoxNzQ4MzUyMzQ0LCJleHAiOjE3NDgzNTI5NDR9.udlRY2YOaFhcs5mhGk_M2AEZT4FvOpygu293ZEmJMtw

{
  "title": "My First Post",
  "content": "This is the content of my first post."
}

### Get all posts
GET http://localhost:3000/posts

### Get post by ID
GET http://localhost:3000/posts/6835bd714050f01eefc8f005

### Get posts by sender
GET http://localhost:3000/posts?sender=6835bd714050f01eefc8f005

### Update a post with an access token
PUT http://localhost:3000/posts/6835bd714050f01eefc8f005
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjk1NjM3OCwiaWF0IjoxNzQ4MzUyMzQ0LCJleHAiOjE3NDgzNTI5NDR9.udlRY2YOaFhcs5mhGk_M2AEZT4FvOpygu293ZEmJMtw

{
  "title": "Updated Title",
  "content": "Updated content of the post."
}

### Delete a post with an access token
DELETE http://localhost:3000/posts/6835bd714050f01eefc8f005
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjk1NjM3OCwiaWF0IjoxNzQ4MzUyMzQ0LCJleHAiOjE3NDgzNTI5NDR9.udlRY2YOaFhcs5mhGk_M2AEZT4FvOpygu293ZEmJMtw

### Create a new comment with an access token
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjYwNjU2OSwiaWF0IjoxNzQ4MzUyNzIzLCJleHAiOjE3NDgzNTMzMjN9.mbrSqVhIS-ZbM2fjC3qhD9iYtdMM2wLHL5s9O8sJSo4

{
  "comment": "This is a comment",
  "postId": "678cf8f146946bf2f9dd16c0"
}

### Get all comments
GET http://localhost:3000/comments

### Get comments by postId
GET http://localhost:3000/comments/posts/6835bef31ffa5ead1e16e4b3

### Get comment by ID
GET http://localhost:3000/comments/6835bef31ffa5ead1e16e4b3

### Update comment with an access token
PUT http://localhost:3000/comments/6835bef31ffa5ead1e16e4b3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjYwNjU2OSwiaWF0IjoxNzQ4MzUyNzIzLCJleHAiOjE3NDgzNTMzMjN9.mbrSqVhIS-ZbM2fjC3qhD9iYtdMM2wLHL5s9O8sJSo4

{
  "comment": "This is the updated comment content"
}

### Delete comment with an access token
DELETE http://localhost:3000/comments/6835bef31ffa5ead1e16e4b3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjYwNjU2OSwiaWF0IjoxNzQ4MzUyNzIzLCJleHAiOjE3NDgzNTMzMjN9.mbrSqVhIS-ZbM2fjC3qhD9iYtdMM2wLHL5s9O8sJSo4

### Logout a user
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjM2MTMzOSwiaWF0IjoxNzQ4MzUyOTUzLCJleHAiOjE3NDg5NTc3NTN9.wum23VwRHqS821fMVeNnZUWf1UYN4IMirCRhgUYP23M"
}