### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "fullName": "Ilana Barkin",
  "email": "ilana100@gmail.com",
  "password": "1234"
  
}

### Login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ilana100@gmail.com",
  "password": "1234"
}

### Refresh a user token
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGQxNTg3NzJkY2M5OTY1ZTZhNzdjODciLCJyYW5kb20iOjE2MjU1MSwiaWF0IjoxNzU4NTUwMTUxLCJleHAiOjE3NTg3MjI5NTF9.QGQDNFUqi3m3qHmSCMNGWlhKPmzliqr_bDRXTjLEM2s"
}

### Create a new post with an access token
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODUyZDQzYmQzOTNlMWY3MGJlM2RhN2QiLCJyYW5kb20iOjY2NDg5NywiaWF0IjoxNzUwMjU5MTEzLCJleHAiOjE3NTAzNDU1MTN9.TL_MTacki1WkQU4lH_WtSqWfQKCnTDyUgFIRalW0ZPc

{
  "title": "My First Post",
  "description": "A short description of the post",
  "review": "This is the full review content of the post"
}

### Get all posts
GET http://localhost:3000/posts

### Get post by ID
GET http://localhost:3000/posts/6852d54bc34778ef86fa1c21

### Get posts by sender
GET http://localhost:3000/posts?sender=6835bd714050f01eefc8f005

### Update a post with an access token
PUT http://localhost:3000/posts/6835bd714050f01eefc8f005
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjk1NjM3OCwiaWF0IjoxNzQ4MzUyMzQ0LCJleHAiOjE3NDgzNTI5NDR9.udlRY2YOaFhcs5mhGk_M2AEZT4FvOpygu293ZEmJMtw

{
  "title": "Updated Title",
  "content": "Updated content of the post."
}

### Delete a post with an access token
DELETE http://localhost:3000/posts/6835bd714050f01eefc8f005
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjk1NjM3OCwiaWF0IjoxNzQ4MzUyMzQ0LCJleHAiOjE3NDgzNTI5NDR9.udlRY2YOaFhcs5mhGk_M2AEZT4FvOpygu293ZEmJMtw

### Create a new comment with an access token
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjYwNjU2OSwiaWF0IjoxNzQ4MzUyNzIzLCJleHAiOjE3NDgzNTMzMjN9.mbrSqVhIS-ZbM2fjC3qhD9iYtdMM2wLHL5s9O8sJSo4

{
  "comment": "This is a comment",
  "postId": "678cf8f146946bf2f9dd16c0"
}

### Get all comments
GET http://localhost:3000/comments

### Get comments by postId
GET http://localhost:3000/comments/posts/6835bef31ffa5ead1e16e4b3

### Get comment by ID
GET http://localhost:3000/comments/6835bef31ffa5ead1e16e4b3

### Update comment with an access token
PUT http://localhost:3000/comments/6835bef31ffa5ead1e16e4b3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjYwNjU2OSwiaWF0IjoxNzQ4MzUyNzIzLCJleHAiOjE3NDgzNTMzMjN9.mbrSqVhIS-ZbM2fjC3qhD9iYtdMM2wLHL5s9O8sJSo4

{
  "comment": "This is the updated comment content"
}

### Delete comment with an access token
DELETE http://localhost:3000/comments/6835bef31ffa5ead1e16e4b3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjYwNjU2OSwiaWF0IjoxNzQ4MzUyNzIzLCJleHAiOjE3NDgzNTMzMjN9.mbrSqVhIS-ZbM2fjC3qhD9iYtdMM2wLHL5s9O8sJSo4

### Logout a user
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODM1YWQxZmFkMjMwYzhiMDc3NGQxZTgiLCJyYW5kb20iOjM2MTMzOSwiaWF0IjoxNzQ4MzUyOTUzLCJleHAiOjE3NDg5NTc3NTN9.wum23VwRHqS821fMVeNnZUWf1UYN4IMirCRhgUYP23M"
}