### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "fullName": "Ilana Barkin",
  "email": "ilana100@gmail.com",
  "password": "1234"
  
}

### Login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ilana100@gmail.com",
  "password": "1234"
}

### Refresh a user token
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE2Y2ZjNGZhMDk4NTBiY2Y4MGNlODAiLCJyYW5kb20iOjkwNTM0LCJpYXQiOjE3NzI1NDAwNDYsImV4cCI6MTc3MzE0NDg0Nn0.DwAW5jckJsDvT1TYMcWK77VESIGMsYwxV2taHCd_2Xs"
}

### Create a new post with an access token
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE2Y2ZjNGZhMDk4NTBiY2Y4MGNlODAiLCJyYW5kb20iOjg0Njc5MCwiaWF0IjoxNzcyNTM5ODYzLCJleHAiOjE3NzI1NDA0NjN9.V6mo5wve9L5c2phQa-SdKLGjKYZ2TIkoukZgmU-QIMM

{
  "title": "My First Post",
  "description": "A short description of the post",
  "review": "This is the full review content of the post"
}

### Get all posts
GET http://localhost:3000/posts

### Get post by ID
GET http://localhost:3000/posts/69a6d101fa09850bcf80ce97

### Get posts by sender
GET http://localhost:3000/posts?sender=69a6d101fa09850bcf80ce97

### Update a post with an access token
PUT http://localhost:3000/posts/69a6d101fa09850bcf80ce97
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE2Y2ZjNGZhMDk4NTBiY2Y4MGNlODAiLCJyYW5kb20iOjg0Njc5MCwiaWF0IjoxNzcyNTM5ODYzLCJleHAiOjE3NzI1NDA0NjN9.V6mo5wve9L5c2phQa-SdKLGjKYZ2TIkoukZgmU-QIMM

{
  "title": "Updated Title",
  "content": "Updated content of the post."
}

### Delete a post with an access token
DELETE http://localhost:3000/posts/69a6d101fa09850bcf80ce97
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE2Y2ZjNGZhMDk4NTBiY2Y4MGNlODAiLCJyYW5kb20iOjg0Njc5MCwiaWF0IjoxNzcyNTM5ODYzLCJleHAiOjE3NzI1NDA0NjN9.V6mo5wve9L5c2phQa-SdKLGjKYZ2TIkoukZgmU-QIMM

### Create a new comment with an access token
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE2Y2ZjNGZhMDk4NTBiY2Y4MGNlODAiLCJyYW5kb20iOjg0Njc5MCwiaWF0IjoxNzcyNTM5ODYzLCJleHAiOjE3NzI1NDA0NjN9.V6mo5wve9L5c2phQa-SdKLGjKYZ2TIkoukZgmU-QIMM

{
  "comment": "This is a comment",
  "postId": "678cf8f146946bf2f9dd16c0"
}

### Get all comments
GET http://localhost:3000/comments

### Get comments by postId
GET http://localhost:3000/comments/posts/69a6d101fa09850bcf80ce97

### Get comment by ID
GET http://localhost:3000/comments/68d179c93a46ed68097c399c

### Update comment with an access token
PUT http://localhost:3000/comments/68d179c93a46ed68097c399c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE2Y2ZjNGZhMDk4NTBiY2Y4MGNlODAiLCJyYW5kb20iOjg0Njc5MCwiaWF0IjoxNzcyNTM5ODYzLCJleHAiOjE3NzI1NDA0NjN9.V6mo5wve9L5c2phQa-SdKLGjKYZ2TIkoukZgmU-QIMM

{
  "comment": "This is the updated comment content"
}

### Delete comment with an access token
DELETE http://localhost:3000/comments/68d179c93a46ed68097c399c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE2Y2ZjNGZhMDk4NTBiY2Y4MGNlODAiLCJyYW5kb20iOjg0Njc5MCwiaWF0IjoxNzcyNTM5ODYzLCJleHAiOjE3NzI1NDA0NjN9.V6mo5wve9L5c2phQa-SdKLGjKYZ2TIkoukZgmU-QIMM

### Logout a user
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWE2Y2ZjNGZhMDk4NTBiY2Y4MGNlODAiLCJyYW5kb20iOjg0Njc5MCwiaWF0IjoxNzcyNTM5ODYzLCJleHAiOjE3NzMxNDQ2NjN9.xN5xYbpfu2Q8tgOkHjuoqXEUYDYsQaqZ7xTuixzsAn8"
}